version: "3"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    network_mode: host
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DOCKER_USER=$USER
      - PASSWORD="secure password" #optional
      - SUDO_PASSWORD='super secure password' #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - $HOME/.local:/home/coder/.local
      - $HOME/.config:/home/coder/.config
      - $PWD:/home/coder/project
    restart: unless-stopped